// <auto-generated />
namespace lab6_DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fif : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fif));
        
        string IMigrationMetadata.Id
        {
            get { return "202103240547236_fif"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
